[package]
name = "kat"
version = "0.1.0"
authors = ["coleman"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
molt = "0.2.2"
molt-shell = "0.2.2"
thiserror = "1.0.10"
